/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  MockForwarder,
  MockForwarderInterface,
} from "../../test/MockForwarder";

const _abi = [
  {
    inputs: [
      {
        internalType: "bool",
        name: "result_",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161026b38038061026b8339818101604052810190610032919061008e565b806000806101000a81548160ff021916908315150217905550506100bb565b600080fd5b60008115159050919050565b61006b81610056565b811461007657600080fd5b50565b60008151905061008881610062565b92915050565b6000602082840312156100a4576100a3610051565b5b60006100b284828501610079565b91505092915050565b6101a1806100ca6000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80638e760afe14610030575b600080fd5b61004a600480360381019061004591906100e8565b610060565b6040516100579190610150565b60405180910390f35b60008060009054906101000a900460ff16905092915050565b600080fd5b600080fd5b600080fd5b600080fd5b600080fd5b60008083601f8401126100a8576100a7610083565b5b8235905067ffffffffffffffff8111156100c5576100c4610088565b5b6020830191508360018202830111156100e1576100e061008d565b5b9250929050565b600080602083850312156100ff576100fe610079565b5b600083013567ffffffffffffffff81111561011d5761011c61007e565b5b61012985828601610092565b92509250509250929050565b60008115159050919050565b61014a81610135565b82525050565b60006020820190506101656000830184610141565b9291505056fea264697066735822122071622192fee021632e23227d54b44195c145ea1439c244e0d4e22736077ed83264736f6c63430008180033";

type MockForwarderConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockForwarderConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockForwarder__factory extends ContractFactory {
  constructor(...args: MockForwarderConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    result_: boolean,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(result_, overrides || {});
  }
  override deploy(
    result_: boolean,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(result_, overrides || {}) as Promise<
      MockForwarder & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockForwarder__factory {
    return super.connect(runner) as MockForwarder__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockForwarderInterface {
    return new Interface(_abi) as MockForwarderInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockForwarder {
    return new Contract(address, _abi, runner) as unknown as MockForwarder;
  }
}
