/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IKeystoneForwarder,
  IKeystoneForwarderInterface,
} from "../../ProofEscrow.sol/IKeystoneForwarder";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IKeystoneForwarder__factory {
  static readonly abi = _abi;
  static createInterface(): IKeystoneForwarderInterface {
    return new Interface(_abi) as IKeystoneForwarderInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IKeystoneForwarder {
    return new Contract(address, _abi, runner) as unknown as IKeystoneForwarder;
  }
}
